const questionLanguage = {
  'EQ-HYP-001': ['Как недельный объём подходов влияет на гипертрофию?', 'Сколько рабочих подходов в неделю нужно мышце для роста?', 'How many weekly working sets does a muscle need to grow?'],
  'EQ-HYP-002': ['Нужно ли доводить рабочие подходы до мышечного отказа?', 'Нужно ли делать каждый подход до отказа для роста мышц?', 'Do you need to take every set to failure to build muscle?'],
  'EQ-HYP-003': ['Как нагрузка и диапазон повторений влияют на гипертрофию и силу?', 'С каким весом и числом повторений лучше тренироваться для мышц и силы?', 'What weight and repetition range should you use for muscle and strength?'],
  'EQ-HYP-004': ['Имеет ли значение частота тренировки мышцы при равном объёме?', 'Сколько раз в неделю нужно тренировать одну мышцу?', 'How many times per week should you train a muscle?'],
  'EQ-HYP-005': ['Сколько отдыхать между рабочими подходами?', 'Сколько отдыхать между подходами, чтобы следующий подход оставался качественным?', 'How long should you rest so the next set stays effective?'],
  'EQ-PRG-001': ['Как прогрессировать нагрузку, повторения и объём?', 'Когда увеличивать вес, повторения или число подходов?', 'When should you add weight, repetitions, or sets?'],
  'EQ-HYP-006': ['Как полная и частичная амплитуда влияют на адаптацию?', 'Нужно ли всегда делать движение полностью или иногда полезна только его часть?', 'Should you always use the full movement, or can part of it sometimes help?'],
  'EQ-PRG-002': ['Как порядок упражнений влияет на силу и гипертрофию?', 'Какие упражнения лучше ставить в начало тренировки?', 'Which exercises should come first in a workout?'],
  'EQ-PRG-003': ['Улучшают ли периодизация и плановые разгрузки результаты?', 'Нужно ли заранее менять нагрузку и планировать лёгкие недели?', 'Do you need planned training changes and easier weeks?'],
  'EQ-CON-001': ['Когда аэробная нагрузка мешает адаптации к силовым тренировкам?', 'Когда кардио может мешать росту мышц, силы или мощности?', 'When can cardio interfere with muscle, strength, or power gains?'],
}

const claimLanguage = {
  'ECV-WEEKLY-VOLUME-HYP-v1': ['Больший недельный объём тяжёлых подходов в среднем связан с большей гипертрофией, но отдача снижается, а универсальной верхней границы нет.', 'Больше качественных рабочих подходов за неделю в среднем помогает мышцам расти, но каждый следующий подход приносит меньше пользы. Единого лучшего числа для всех нет.', 'More quality weekly working sets generally support more muscle growth, but each additional set adds less benefit and there is no single best number for everyone.'],
  'ECV-RIR-HYP-v1': ['Для гипертрофии не обязательно доходить до точного мышечного отказа, однако постоянная остановка очень далеко от отказа может быть менее эффективной.', 'Для роста мышц не обязательно делать каждый подход до отказа. Но подходы, которые заканчиваются слишком легко, могут давать меньше стимула.', 'You do not need to take every set to failure to build muscle, but sets that finish too easily may provide less stimulus.'],
  'ECV-LOAD-GOAL-v1': ['Широкий диапазон нагрузок при достаточном усилии может поддерживать гипертрофию, а тяжёлая специфичная практика лучше способствует максимальной силе.', 'Мышцы могут расти с разными рабочими весами, если подход достаточно трудный. Для роста максимальной силы важна отдельная практика с тяжёлыми весами.', 'Muscle can grow with a range of weights when sets are sufficiently hard; maximal strength also benefits from specific practice with heavy weights.'],
  'ECV-FREQUENCY-HYP-v1': ['При равном недельном объёме частота тренировок не оказывает явно выраженного самостоятельного влияния на гипертрофию.', 'Если недельное число качественных подходов одинаково, само по себе количество тренировок мышцы обычно не даёт большого преимущества в росте.', 'When weekly quality-set volume is the same, the number of sessions per muscle does not appear to add a large growth benefit by itself.'],
  'ECV-REST-HYP-v1': ['Отдых дольше совсем коротких интервалов может немного способствовать гипертрофии за счёт сохранения качества следующих подходов, но универсального оптимума не установлено.', 'Слишком короткий отдых может ухудшить следующие подходы. Лучше отдыхать достаточно для сохранения качества, но одной идеальной длительности для всех нет.', 'Very short rests can reduce the quality of later sets; resting long enough to recover is useful, but there is no single ideal duration for everyone.'],
  'ECV-PROGRESSION-METHOD-v1': ['Увеличение веса и увеличение повторений могут поддерживать рост силы и мышц; универсальное превосходство одного метода не установлено.', 'Прогрессировать можно и добавляя вес, и делая больше повторений. Нет доказательств, что один из этих способов всегда лучше.', 'You can progress by adding weight or repetitions; neither method is proven universally better.'],
  'ECV-PROGRESSION-ALGORITHM-v1': ['Доказательств недостаточно, чтобы назвать одну точную последовательность изменения веса, повторений и подходов оптимальной для всех.', 'Исследования пока не позволяют назвать один лучший порядок, в котором всем нужно добавлять вес, повторения и подходы.', 'Research does not identify one best sequence for adding weight, repetitions, and sets for everyone.'],
  'ECV-ROM-FULL-DEFAULT-v1': ['Полная амплитуда — более надёжная общая стратегия, чем произвольно сокращённая, особенно для силы и гипертрофии нижней части тела.', 'Полное контролируемое движение — более надёжный вариант по умолчанию, чем повторения только в короткой части движения, особенно для мышц нижней части тела.', 'A controlled full movement is a more reliable default than training only a shortened part of the movement, especially for lower-body muscles.'],
  'ECV-ROM-LENGTHENED-PARTIAL-v1': ['В изученных сравнениях полная амплитуда и работа в растянутой части движения обычно давали больший рост ряда измеренных мышц, чем работа только в сокращённой части; универсального превосходства растянутых частичных повторений над полной амплитудой не установлено.', 'Полное движение и повторения в растянутой части обычно выглядят лучше повторений только в сокращённой части. Но исследования не показывают, что растянутые частичные повторения всегда лучше полного движения.', 'Full movement and repetitions in the lengthened part generally look better than training only the shortened part; research does not show that lengthened partials are always better than full movement.'],
  'ECV-ROM-CALF-LENGTHENED-v1': ['У молодых женщин частичные подъёмы на носки в растянутой части движения дали больший рост медиальной икроножной мышцы, чем полная и сокращённая частичная амплитуда; для латеральной головки преимущество над полной амплитудой осталось неопределённым.', 'В одном восьминедельном исследовании нижняя часть подъёма на носки лучше увеличила измеренную толщину внутренней головки икроножной мышцы. Для внешней головки явного преимущества перед полным движением не показано.', 'In one eight-week study of young women, the lengthened portion of a calf raise increased medial gastrocnemius thickness more than full or shortened partial ROM; superiority over full ROM was unclear for the lateral gastrocnemius.'],
  'ECV-ROM-ARMS-LENGTHENED-v1': ['У тренированных взрослых восемь недель работы в растянутой частичной и полной амплитуде дали в целом сходный рост измеренных участков сгибателей и разгибателей локтя; небольшое локальное преимущество partial ROM в одном исследовании не подтверждает превосходство для всей мышцы.', 'Для бицепса, плечевой мышцы и трицепса растянутые частичные и полные повторения в новых исследованиях дали в целом похожий рост. Небольшая разница в одном участке бицепса пока не означает, что частичные повторения лучше для рук в целом.', 'In trained adults, eight weeks of lengthened-partial and full-ROM training produced broadly similar growth at measured elbow-flexor and elbow-extensor sites; a small regional difference in one study does not establish whole-muscle superiority.'],
  'ECV-ROM-QUAD-LENGTHENED-v1': ['В одном восьминедельном исследовании разгибания колена частичная амплитуда на длинной длине мышцы и полная амплитуда дали сходный рост толщины латеральной широкой мышцы бедра во всех точках; обе превосходили укороченную частичную амплитуду в отдельных точках.', 'В разгибании колена полное движение и повторения в растянутой части дали похожий рост измеренных участков наружной части квадрицепса. Повторения только в сокращённой части выглядели хуже в некоторых точках.', 'In one eight-week knee-extension study, lengthened-partial and full ROM produced similar vastus lateralis thickness growth at all measured sites; both outperformed shortened partial ROM at selected sites.'],
  'ECV-ORDER-STRENGTH-PRIORITY-v1': ['Размещение приоритетного упражнения в начале тренировки обычно способствует большему приросту силы именно в нём.', 'Упражнение, в котором важнее всего стать сильнее, обычно стоит выполнять ближе к началу тренировки.', 'The exercise in which strength matters most should generally be performed earlier in the workout.'],
  'ECV-ORDER-HYPERTROPHY-v1': ['Явного преимущества для гипертрофии у порядка «многосуставные сначала» по сравнению с «односуставные сначала» не показано.', 'Для роста мышц не показано, что базовые упражнения всегда нужно выполнять раньше изолирующих.', 'For muscle growth, evidence does not show that compound exercises must always come before isolation exercises.'],
  'ECV-PERIODIZATION-OUTCOMES-v1': ['При равном объёме периодизация может немного улучшать силу в 1ПМ, особенно у тренированных, но явного преимущества для гипертрофии нет.', 'Плановая смена нагрузки может немного помогать росту максимальной силы, особенно у тренированных, но явного дополнительного роста мышц не показано.', 'Planned variation may modestly help maximal strength, especially in trained lifters, but has not shown a clear extra muscle-growth benefit.'],
  'ECV-DELOAD-PLANNED-v1': ['Доказательств недостаточно, чтобы считать разгрузки по фиксированному графику необходимыми или лучшими для всех.', 'Нет достаточных данных, что всем нужна лёгкая неделя через одинаковое число недель.', 'There is not enough evidence that everyone needs an easier week on the same fixed schedule.'],
  'ECV-CONCURRENT-STRENGTH-HYP-v1': ['Совмещение аэробных и силовых тренировок в среднем не показывает значимого ухудшения гипертрофии или максимальной силы у здоровых взрослых.', 'В среднем кардио вместе с силовыми тренировками не мешает росту мышц или максимальной силы у здоровых взрослых.', 'On average, combining cardio and resistance training does not meaningfully reduce muscle or maximal-strength gains in healthy adults.'],
  'ECV-CONCURRENT-POWER-SCHEDULE-v1': ['Развитие взрывной силы может ослабляться, когда выносливость и силовая работа выполняются в одной сессии; разнесение на несколько часов может снизить риск.', 'Тяжёлое кардио и силовая работа в одной тренировке могут немного мешать развитию взрывной силы. Разделение по времени может снизить этот риск.', 'Hard endurance and resistance work in the same session may slightly reduce power gains; separating them may reduce that risk.'],
}

const includedStudyCounts = {
  'RW-ROM-PALLARES-2021': 16,
  'RW-ROM-KASSIANO-2023': 11,
  'RW-ROM-WOLF-LONGITUDINAL-2025': 8,
  'RW-ROM-REGIONAL-META-2025': 12,
}

const questionSearchQueries = {
  'EQ-HYP-006': [
    '(("range of motion"[Title/Abstract] OR "lengthened partial"[Title/Abstract] OR "long muscle length"[Title/Abstract]) AND ("resistance training"[Title/Abstract] OR "resistance exercise"[Title/Abstract]) AND (hypertrophy[Title/Abstract] OR "muscle thickness"[Title/Abstract] OR "cross-sectional area"[Title/Abstract])) AND ("2022/05/01"[Date - Publication] : "2026/08/06"[Date - Publication])',
  ],
}

const question = (id, topic, questionText, outcomes, critical, reviewIntervalMonths) => ({
  id,
  topic,
  question: questionText,
  questionRu: questionLanguage[id][0],
  plainQuestion: questionLanguage[id][2],
  plainQuestionRu: questionLanguage[id][1],
  outcomes,
  critical,
  reviewIntervalMonths,
  scope: 'Healthy adults; treatment, rehabilitation and acute injuries are out of scope.',
  scopeRu: 'Здоровые взрослые; лечение, реабилитация и острые травмы не входят в область рассмотрения.',
  searchStrategy: {
    databases: ['PubMed/MEDLINE', 'publisher and DOI records'],
    queries: questionSearchQueries[id] || [questionText],
    supplementaryMethods: ['reference-list checks', 'known guideline and review checks'],
  },
  searchDate: id === 'EQ-HYP-006' ? '2026-08-06' : '2026-08-02',
  searchNotes: id === 'EQ-HYP-006'
    ? 'Updated discovery scan through 2026-08-06. Full export, PRISMA counts, exclusion reasons and deduplication are required before approval.'
    : 'Rapid editorial scan, not a systematic review. Screening totals and deduplicated primary-study counts were not recorded in phase 0.',
})

const work = (id, title, year, workType, identifiers, reviewScope = 'abstract_only') => ({
  id,
  status: 'screened_in',
  title,
  year,
  workType,
  identifiers,
  correctionStatus: 'unknown',
  reviewScope,
  ...(includedStudyCounts[id] ? { includedStudiesCount: includedStudyCounts[id] } : {}),
  sourceNotes: 'Draft pilot import; full status, license and conflict checks are required before approval.',
})

const assessment = (id, questionId, workId, outcomes, mainResult) => ({
  id,
  questionId,
  workId,
  status: 'draft',
  reviewScope: 'abstract_only',
  population: 'Healthy adults in the populations represented by the source.',
  outcomes,
  mainResults: [mainResult],
  directness: 'some_concerns',
  riskOfBias: 'not_assessed',
  limitations: ['Formal full-text and supplement appraisal has not been completed.'],
  cannotSupport: ['An individual optimum or guaranteed outcome.'],
})

const claim = ({
  id,
  claimId,
  questionId,
  statement,
  outcomes,
  effect,
  certainty,
  evidence,
  population = 'Healthy adults.',
  trainingStatuses = ['mixed'],
  bodyScopes = ['whole_body'],
  muscles = [],
  muscleRegions = [],
  exercises = [],
  romSegments = [],
  measurementMethods = [],
  applicabilityNotes = [],
  limitations = ['Evidence is heterogeneous and does not define an individual optimum.'],
  unknowns = ['Individual response and long-term effects remain uncertain.'],
  searchCutoff = '2026-08-02',
}) => ({
  id,
  claimId,
  questionId,
  version: 1,
  status: 'draft',
  statement,
  statementRu: claimLanguage[id][0],
  plainStatement: claimLanguage[id][2],
  plainStatementRu: claimLanguage[id][1],
  population,
  trainingStatuses,
  bodyScopes,
  outcomes,
  muscles,
  muscleRegions,
  exercises,
  romSegments,
  measurementMethods,
  applicabilityNotes,
  effect,
  certainty,
  certaintyRationale: 'Rapid editorial synthesis; scientific review is required before runtime use.',
  limitations,
  unknowns,
  evidence: { supports: [], contradicts: [], contextualizes: [], ...evidence },
  searchCutoff,
  reviewDueAt: '2027-02-02',
  createdBy: 'evidence-pilot',
})

const recommendation = ({
  id,
  claimVersionId,
  supportingClaimVersionIds = [],
  guidance,
  heuristic,
  forbidden,
  surfaces = ['ai_trainer', 'program_generation', 'blog'],
}) => ({
  id,
  claimVersionId,
  supportingClaimVersionIds,
  status: 'draft',
  surfaces,
  audience: 'Healthy adults using AI Trainer for general resistance training.',
  guidance,
  implementationHeuristic: heuristic,
  strength: 'conditional',
  exceptions: ['Clinical, rehabilitation or acute-injury context.'],
  safetyNotes: ['Pain or loss of safe technique overrides progression guidance.'],
  allowedWording: ['Use probabilistic wording and identify product defaults as heuristics.'],
  forbiddenWording: [forbidden],
  reviewDueAt: '2027-02-02',
})

const questions = [
  question('EQ-HYP-001', 'weekly_volume', 'How does weekly set volume affect hypertrophy?', ['hypertrophy'], true, 6),
  question('EQ-HYP-002', 'proximity_to_failure', 'Must working sets reach momentary muscular failure?', ['hypertrophy', 'maximal_strength', 'fatigue'], true, 6),
  question('EQ-HYP-003', 'load_and_repetitions', 'How do load and repetition range affect hypertrophy and strength?', ['hypertrophy', 'maximal_strength'], true, 12),
  question('EQ-HYP-004', 'frequency', 'Does muscle-training frequency matter when volume is equated?', ['hypertrophy', 'maximal_strength'], false, 12),
  question('EQ-HYP-005', 'inter_set_rest', 'How long should rest between working sets be?', ['hypertrophy', 'maximal_strength', 'fatigue'], false, 12),
  question('EQ-PRG-001', 'progression', 'How should load, repetitions and volume progress?', ['hypertrophy', 'exercise_specific_strength', 'adherence', 'fatigue'], true, 12),
  question('EQ-HYP-006', 'range_of_motion', 'How do full and partial ranges of motion affect adaptations?', ['hypertrophy', 'exercise_specific_strength'], false, 6),
  question('EQ-PRG-002', 'exercise_order', 'How does exercise order affect strength and hypertrophy?', ['hypertrophy', 'exercise_specific_strength'], false, 18),
  question('EQ-PRG-003', 'periodization_and_deload', 'Do periodization and planned deloads improve outcomes?', ['hypertrophy', 'maximal_strength', 'fatigue'], false, 12),
  question('EQ-CON-001', 'concurrent_training', 'When does aerobic work interfere with resistance adaptations?', ['hypertrophy', 'maximal_strength', 'power'], true, 12),
]

const works = [
  work('RW-ACSM-2026', 'Resistance Training Prescription for Muscle Function, Hypertrophy, and Physical Performance in Healthy Adults', 2026, 'position_stand', { doi: '10.1249/MSS.0000000000003897', pmid: '41843416', pmcid: 'PMC12965823' }, 'full_text'),
  work('RW-VOLUME-2026', 'The Resistance Training Dose Response: Meta-Regressions Exploring Weekly Volume and Frequency', 2026, 'meta_analysis', { doi: '10.1007/s40279-025-02344-w', pmid: '41343037' }),
  work('RW-PRESCRIPTION-2023', 'Resistance training prescription for muscle strength and hypertrophy in healthy adults', 2023, 'meta_analysis', { doi: '10.1136/bjsports-2023-106807', pmid: '37414459' }),
  work('RW-RIR-METAREG-2024', 'Dose-Response Between Proximity to Failure, Strength Gain, and Hypertrophy', 2024, 'meta_analysis', { doi: '10.1007/s40279-024-02069-2', pmid: '38970765' }),
  work('RW-FAILURE-META-2022', 'Resistance Training to Repetition Failure or Non-Failure', 2022, 'meta_analysis', { doi: '10.1016/j.jshs.2021.01.007', pmid: '33497853', pmcid: 'PMC9068575' }),
  work('RW-RIR-RCT-2024', 'Similar hypertrophy after training to failure or with repetitions in reserve', 2024, 'rct', { doi: '10.1080/02640414.2024.2321021', pmid: '38393985' }),
  work('RW-LOAD-NMA-2021', 'Resistance Training Load Effects on Muscle Hypertrophy and Strength Gain', 2021, 'meta_analysis', { doi: '10.1249/MSS.0000000000002585', pmid: '33433148', pmcid: 'PMC8126497' }),
  work('RW-FREQUENCY-META-2019', 'How many times per week should a muscle be trained?', 2019, 'meta_analysis', { doi: '10.1080/02640414.2018.1555906', pmid: '30558493' }),
  work('RW-REST-META-2024', 'Give it a rest: inter-set rest interval duration and hypertrophy', 2024, 'meta_analysis', { doi: '10.3389/fspor.2024.1429789', pmid: '39205815', pmcid: 'PMC11349676' }),
  work('RW-PROG-CHAVES-2024', 'Effects of Resistance Training Overload Progression Protocols', 2024, 'rct', { doi: '10.1055/a-2256-5857', pmid: '38286426' }),
  work('RW-PROG-PLOTKIN-2022', 'Progressive overload without progressing load?', 2022, 'rct', { doi: '10.7717/peerj.14142', pmid: '36199287', pmcid: 'PMC9528903' }),
  work('RW-ROM-PALLARES-2021', 'Effects of range of motion on resistance training adaptations', 2021, 'meta_analysis', { doi: '10.1111/sms.14006', pmid: '34170576' }),
  work('RW-ROM-KASSIANO-2023', 'Which ROMs Lead to Rome?', 2023, 'systematic_review', { doi: '10.1519/JSC.0000000000004415', pmid: '36662126' }),
  work('RW-ROM-KASSIANO-CALF-2023', 'Greater Gastrocnemius Muscle Hypertrophy After Partial Range of Motion Training Performed at Long Muscle Lengths', 2023, 'rct', { doi: '10.1519/JSC.0000000000004460', pmid: '37015016' }),
  work('RW-ROM-WOLF-UPPER-2025', 'Lengthened partial repetitions elicit similar muscular adaptations as full range of motion repetitions during resistance training in trained individuals', 2025, 'rct', { doi: '10.7717/peerj.18904', pmid: '39959841', pmcid: 'PMC11829627' }),
  work('RW-ROM-HAVERS-BICEPS-2025', 'Partial Range, Full Gains? The Effect of 8 Weeks of Partial Range of Motion Training at Long Muscle Lengths on Elbow Flexor Hypertrophy and Strength in Trained Individuals', 2025, 'rct', { doi: '10.1002/ejsc.70087', pmid: '41247250', pmcid: 'PMC12621570', trialId: 'DRKS00035811' }),
  work('RW-ROM-GSCHNEIDNER-2025', 'The effects of lengthened-partial range of motion resistance training of the limbs on arm and thigh muscle area: A multi-site randomised trial', 2025, 'rct', { doi: '10.1080/02640414.2025.2567805', pmid: '41055237' }),
  work('RW-ROM-VAROVIC-2025', 'The effects of long muscle length isometric versus full range of motion isotonic training on regional quadriceps femoris hypertrophy in resistance-trained individuals', 2025, 'rct', { doi: '10.1139/apnm-2025-0238', pmid: '40911904' }),
  work('RW-ROM-WOLF-LONGITUDINAL-2025', 'Does longer-muscle length resistance training cause greater longitudinal growth in humans?', 2025, 'systematic_review', { doi: '10.1016/j.smhs.2025.03.001', pmid: '41646176', pmcid: 'PMC12869050' }),
  work('RW-ROM-REGIONAL-META-2025', 'Does Muscle Length Influence Regional Hypertrophy?', 2025, 'meta_analysis', { doi: '10.1055/a-2615-4935', pmid: '40570881' }),
  work('RW-ROM-MCMAHON-2026', 'Moderate Intensity Resistance Training With Partial Range-of-Motion at Long Muscle Lengths Elicits Similar Hypertrophy and Architectural Adaptations as High Intensity Resistance Training Using Full Range-of-Motion', 2026, 'rct', { doi: '10.1519/JSC.0000000000005561', pmid: '42392615' }),
  work('RW-ORDER-NUNES-2021', 'What influence does resistance exercise order have?', 2021, 'meta_analysis', { doi: '10.1080/17461391.2020.1733672', pmid: '32077380' }),
  work('RW-PERIOD-MOESGAARD-2022', 'Effects of Periodization on Strength and Muscle Hypertrophy', 2022, 'meta_analysis', { doi: '10.1007/s40279-021-01636-1', pmid: '35044672' }),
  work('RW-DELOAD-COLEMAN-2024', 'Gaining more from doing less?', 2024, 'rct', { doi: '10.7717/peerj.16777', pmid: '38274324', pmcid: 'PMC10809978' }),
  work('RW-DELOAD-PANCAR-2026', 'Effects of deload periods in resistance training', 2026, 'rct', { doi: '10.1038/s41598-026-40612-5', trialId: 'NCT06825052' }),
  work('RW-CON-SCHUMANN-2022', 'Compatibility of Concurrent Aerobic and Strength Training', 2022, 'meta_analysis', { doi: '10.1007/s40279-021-01587-7', pmid: '34757594', pmcid: 'PMC8891239' }),
  work('RW-CON-HELD-2026', 'Maximizing Adaptations in Concurrent Training', 2026, 'umbrella_review', { doi: '10.1007/s40279-026-02401-y', pmid: '41762427' }),
]

const assessments = [
  assessment('RA-VOLUME-HYP', 'EQ-HYP-001', 'RW-VOLUME-2026', ['hypertrophy'], 'Volume has a positive dose-response with diminishing returns.'),
  assessment('RA-RIR-HYP', 'EQ-HYP-002', 'RW-RIR-METAREG-2024', ['hypertrophy', 'maximal_strength'], 'Exact failure is not required; proximity may matter more for hypertrophy than strength.'),
  assessment('RA-LOAD-GOAL', 'EQ-HYP-003', 'RW-LOAD-NMA-2021', ['hypertrophy', 'maximal_strength'], 'A broad load range supports hypertrophy, while heavier practice better supports 1RM strength.'),
  assessment('RA-FREQUENCY-HYP', 'EQ-HYP-004', 'RW-FREQUENCY-META-2019', ['hypertrophy'], 'No clear independent hypertrophy benefit was detected when volume was equated.'),
  assessment('RA-REST-HYP', 'EQ-HYP-005', 'RW-REST-META-2024', ['hypertrophy'], 'Very short rest may be less favorable, but no universal optimum is established.'),
  assessment('RA-PROG-METHOD', 'EQ-PRG-001', 'RW-PROG-CHAVES-2024', ['hypertrophy', 'exercise_specific_strength'], 'Load and repetition progression both improved outcomes in early training.'),
  assessment('RA-ROM-FULL', 'EQ-HYP-006', 'RW-ROM-PALLARES-2021', ['hypertrophy', 'exercise_specific_strength'], 'Full ROM generally outperformed pooled partial ROM conditions.'),
  assessment('RA-ROM-LENGTHENED', 'EQ-HYP-006', 'RW-ROM-KASSIANO-2023', ['hypertrophy'], 'Lengthened partials may be useful for selected muscles and exercises.'),
  { ...assessment('RA-ROM-CALF-2023', 'EQ-HYP-006', 'RW-ROM-KASSIANO-CALF-2023', ['hypertrophy'], 'In young women, lengthened-partial calf raises increased medial gastrocnemius thickness more than full and shortened partial ROM; lateral gastrocnemius was greater than shortened partial but not clearly greater than full ROM.'), population: 'Forty-two young women; 8 weeks of horizontal leg-press calf raises, three sessions per week.', mainResults: ['Medial gastrocnemius: lengthened partial +15.2%, full ROM +6.7%, shortened partial +3.4%.', 'Lateral gastrocnemius: lengthened partial +14.9%, full ROM +7.3%, shortened partial +6.2%; lengthened partial did not clearly differ from full ROM (p=0.060).'], limitations: ['Abstract-only extraction; ultrasound muscle thickness, short intervention, one exercise, young women only.'] },
  { ...assessment('RA-ROM-UPPER-2025', 'EQ-HYP-006', 'RW-ROM-WOLF-UPPER-2025', ['hypertrophy', 'muscular_endurance'], 'Lengthened partial and full ROM produced similar elbow-flexor and elbow-extensor thickness and lat-pulldown strength-endurance adaptations.'), population: 'Thirty resistance-trained adults in a randomized within-participant 8-week upper-body program.', mainResults: ['Point estimates for hypertrophy and 10RM strength-endurance were close to zero between conditions.', 'Bayes factors generally provided moderate support for similar improvement.'], limitations: ['Abstract-only extraction; two ultrasound sites and an eight-week intervention do not establish whole-muscle or long-term equivalence.'] },
  { ...assessment('RA-ROM-BICEPS-2025', 'EQ-HYP-006', 'RW-ROM-HAVERS-BICEPS-2025', ['hypertrophy', 'exercise_specific_strength'], 'Preacher curls with lengthened partial and full ROM produced similar mid-region elbow-flexor growth, with a trivial-to-small advantage for lengthened partial at the distal measurement site.'), population: 'Thirteen resistance-trained adults (11 men, 2 women), randomized within-subject; 8 weeks of unilateral preacher curls.', mainResults: ['Muscle thickness at 50% humeral length improved similarly.', 'At 70%, lengthened partial showed trivial-to-small superiority (SMD 0.10; BF 4.87).', 'Full ROM showed negligible advantages for MVC at 100 degrees and 1RM.'], limitations: ['Small sample, short duration, regional ultrasound outcomes and one exercise.'] },
  { ...assessment('RA-ROM-MULTISITE-2025', 'EQ-HYP-006', 'RW-ROM-GSCHNEIDNER-2025', ['hypertrophy', 'exercise_specific_strength'], 'A large multi-site trial did not establish a clear general hypertrophy advantage of lengthened partial or full ROM for estimated arm and thigh muscle area.'), population: 'Cluster-randomized 12-week trial across 15 sites; 297 participants allocated to lengthened partial or full ROM.', limitations: ['Abstract-only extraction; estimated muscle cross-sectional area from field measurements is not muscle- or region-specific, and strict equivalence criteria were not met.'] },
  { ...assessment('RA-ROM-QUAD-ISOM-2025', 'EQ-HYP-006', 'RW-ROM-VAROVIC-2025', ['hypertrophy'], 'Long-muscle-length isometric and full-ROM isotonic knee extension produced broadly similar regional quadriceps hypertrophy.'), population: 'Resistance-trained adults in a randomized within-subject knee-extension study.', limitations: ['The comparison changes contraction mode as well as ROM; it can contextualize muscle-length evidence but cannot directly establish lengthened-partial versus full-ROM effects.'] },
  { ...assessment('RA-ROM-LONGITUDINAL-REVIEW-2025', 'EQ-HYP-006', 'RW-ROM-WOLF-LONGITUDINAL-2025', ['hypertrophy'], 'Longer-muscle-length training tended to outperform shorter-muscle-length training, but fascicle-length evidence and structural interpretation were mixed.'), population: 'Eight studies, 120 healthy adults.', limitations: ['Narrative systematic review; focused on studies reporting both muscle size and fascicle length, and most fascicle estimates used questionable linear extrapolation.'] },
  { ...assessment('RA-ROM-REGIONAL-META-2025', 'EQ-HYP-006', 'RW-ROM-REGIONAL-META-2025', ['hypertrophy'], 'Longer-muscle-length training showed a small increasing trend toward distal regional hypertrophy, with estimated differences remaining trivial across sites.'), population: 'Twelve studies in young adults.', limitations: ['Combines muscle-length manipulations through ROM and exercise selection; regional trend does not establish that lengthened partials outperform full ROM.'] },
  { ...assessment('RA-ROM-QUAD-2026', 'EQ-HYP-006', 'RW-ROM-MCMAHON-2026', ['hypertrophy'], 'Lengthened-partial and full-ROM knee extension produced similar vastus lateralis thickness at all measured sites; both exceeded shortened partial ROM at selected sites.'), population: 'Forty-five participants randomized across lengthened partial, shortened partial, full ROM and control for 8 weeks of knee extension.', mainResults: ['No muscle-thickness differences between lengthened partial and full ROM at 25%, 50% or 75% femur length.', 'Lengthened partial and full ROM each outperformed shortened partial at selected measurement sites.'], limitations: ['Abstract-only extraction; intervention loads differed between conditions (55% versus 80% 1RM), short duration and one muscle/exercise.'] },
  assessment('RA-ORDER', 'EQ-PRG-002', 'RW-ORDER-NUNES-2021', ['hypertrophy', 'exercise_specific_strength'], 'Exercises performed earlier tended to gain more exercise-specific strength.'),
  assessment('RA-PERIOD', 'EQ-PRG-003', 'RW-PERIOD-MOESGAARD-2022', ['hypertrophy', 'maximal_strength'], 'Periodization may modestly favor 1RM strength but not hypertrophy.'),
  assessment('RA-DELOAD', 'EQ-PRG-003', 'RW-DELOAD-COLEMAN-2024', ['hypertrophy', 'maximal_strength'], 'A week of complete cessation did not improve adaptations and reduced strength gains.'),
  assessment('RA-CONCURRENT', 'EQ-CON-001', 'RW-CON-SCHUMANN-2022', ['hypertrophy', 'maximal_strength', 'power'], 'Hypertrophy and maximal strength were similar; explosive strength showed possible attenuation.'),
]

const claims = [
  claim({ id: 'ECV-WEEKLY-VOLUME-HYP-v1', claimId: 'EC-WEEKLY-VOLUME-HYP', questionId: 'EQ-HYP-001', statement: 'Greater weekly hard-set volume is associated with more hypertrophy on average, with diminishing returns and no universal upper boundary.', outcomes: ['hypertrophy'], effect: 'Positive dose-response with diminishing returns.', certainty: 'moderate', bodyScopes: ['muscle_specific'], evidence: { supports: ['RW-ACSM-2026', 'RW-VOLUME-2026', 'RW-PRESCRIPTION-2023'] } }),
  claim({ id: 'ECV-RIR-HYP-v1', claimId: 'EC-RIR-HYP', questionId: 'EQ-HYP-002', statement: 'Exact momentary failure is not required for hypertrophy, while consistently stopping very far from failure may be less effective.', outcomes: ['hypertrophy', 'fatigue'], effect: 'Near-failure work can be effective without every set reaching failure.', certainty: 'moderate', evidence: { supports: ['RW-RIR-METAREG-2024', 'RW-FAILURE-META-2022', 'RW-RIR-RCT-2024'], contextualizes: ['RW-ACSM-2026'] } }),
  claim({ id: 'ECV-LOAD-GOAL-v1', claimId: 'EC-LOAD-GOAL', questionId: 'EQ-HYP-003', statement: 'A broad range of loads can support hypertrophy with sufficient effort, while heavier specific practice is more favorable for maximal strength.', outcomes: ['hypertrophy', 'maximal_strength'], effect: 'Outcome-specific effect of load.', certainty: 'moderate', evidence: { supports: ['RW-LOAD-NMA-2021', 'RW-PRESCRIPTION-2023'], contextualizes: ['RW-ACSM-2026'] } }),
  claim({ id: 'ECV-FREQUENCY-HYP-v1', claimId: 'EC-FREQUENCY-HYP', questionId: 'EQ-HYP-004', statement: 'When weekly volume is equated, training frequency has no clear large independent effect on hypertrophy.', outcomes: ['hypertrophy'], effect: 'No clear independent hypertrophy effect detected.', certainty: 'moderate', bodyScopes: ['muscle_specific'], evidence: { supports: ['RW-FREQUENCY-META-2019', 'RW-VOLUME-2026', 'RW-PRESCRIPTION-2023'], contextualizes: ['RW-ACSM-2026'] } }),
  claim({ id: 'ECV-REST-HYP-v1', claimId: 'EC-REST-HYP', questionId: 'EQ-HYP-005', statement: 'Rest longer than very short intervals may modestly favor hypertrophy by preserving subsequent set quality, but no universal optimum is established.', outcomes: ['hypertrophy', 'fatigue'], effect: 'Possible small benefit above very short rest intervals.', certainty: 'low', evidence: { supports: ['RW-REST-META-2024'], contextualizes: ['RW-ACSM-2026'] } }),
  claim({ id: 'ECV-PROGRESSION-METHOD-v1', claimId: 'EC-PROGRESSION-METHOD', questionId: 'EQ-PRG-001', statement: 'Increasing load and increasing repetitions can both support strength and muscle-size gains; neither has established universal superiority.', outcomes: ['hypertrophy', 'exercise_specific_strength'], effect: 'Both compared overload methods produced adaptations.', certainty: 'low', bodyScopes: ['exercise_specific', 'muscle_specific'], evidence: { supports: ['RW-PROG-CHAVES-2024', 'RW-PROG-PLOTKIN-2022'] } }),
  claim({ id: 'ECV-PROGRESSION-ALGORITHM-v1', claimId: 'EC-PROGRESSION-ALGORITHM', questionId: 'EQ-PRG-001', statement: 'Evidence is insufficient to identify one exact sequence of load, repetition and set changes as optimal for everyone.', outcomes: ['hypertrophy', 'exercise_specific_strength', 'adherence', 'fatigue'], effect: 'Insufficient comparative evidence.', certainty: 'very_low', evidence: { contextualizes: ['RW-ACSM-2026', 'RW-PROG-CHAVES-2024', 'RW-PROG-PLOTKIN-2022'] } }),
  claim({ id: 'ECV-ROM-FULL-DEFAULT-v1', claimId: 'EC-ROM-FULL-DEFAULT', questionId: 'EQ-HYP-006', statement: 'Full ROM is a more reliable general strategy than arbitrary shortened ROM, particularly for lower-body strength and hypertrophy.', outcomes: ['hypertrophy', 'exercise_specific_strength'], effect: 'Full ROM generally favored over pooled partial-ROM conditions.', certainty: 'moderate', bodyScopes: ['lower_body', 'exercise_specific'], muscles: ['quadriceps femoris', 'gluteus maximus', 'hip adductors'], exercises: ['squat', 'knee extension'], romSegments: ['full', 'shortened_partial'], measurementMethods: ['MRI', 'ultrasound'], applicabilityNotes: ['Muscle-specific results differ; the lower-body finding must not be generalized to every muscle.'], evidence: { supports: ['RW-ROM-PALLARES-2021', 'RW-ROM-KASSIANO-2023'], contextualizes: ['RW-ACSM-2026'] }, searchCutoff: '2026-08-06' }),
  claim({ id: 'ECV-ROM-LENGTHENED-PARTIAL-v1', claimId: 'EC-ROM-LENGTHENED-PARTIAL', questionId: 'EQ-HYP-006', statement: 'Across studied comparisons, full ROM and lengthened-partial ROM generally produced more hypertrophy than shortened-partial ROM for several measured muscles; current evidence does not establish universal superiority of lengthened partials over full ROM.', outcomes: ['hypertrophy'], effect: 'Long-muscle-length training appears more favorable than shortened-position partials; lengthened partial versus full ROM is usually similar with muscle- and site-specific exceptions.', certainty: 'low', bodyScopes: ['muscle_specific', 'exercise_specific'], muscles: ['rectus femoris', 'vastus lateralis', 'biceps brachii', 'brachialis', 'triceps brachii', 'medial gastrocnemius', 'lateral gastrocnemius'], muscleRegions: ['study-specific proximal, middle and distal measurement sites'], exercises: ['knee extension', 'elbow flexion', 'triceps extension', 'calf raise'], romSegments: ['full', 'lengthened_partial', 'middle_partial', 'shortened_partial'], measurementMethods: ['MRI', 'ultrasound'], applicabilityNotes: ['This is a cross-muscle synthesis and must not replace the narrower muscle-specific claims.', 'The evidence concerns measured muscle regions, not necessarily whole-muscle growth.'], evidence: { supports: ['RW-ROM-KASSIANO-2023', 'RW-ROM-WOLF-LONGITUDINAL-2025', 'RW-ROM-REGIONAL-META-2025'], contextualizes: ['RW-ROM-PALLARES-2021', 'RW-ROM-GSCHNEIDNER-2025', 'RW-ROM-VAROVIC-2025'] }, searchCutoff: '2026-08-06' }),
  claim({ id: 'ECV-ROM-CALF-LENGTHENED-v1', claimId: 'EC-ROM-CALF-LENGTHENED', questionId: 'EQ-HYP-006', statement: 'In young women performing horizontal leg-press calf raises for eight weeks, lengthened-partial ROM increased medial gastrocnemius thickness more than full and shortened-partial ROM; superiority over full ROM was uncertain for lateral gastrocnemius.', outcomes: ['hypertrophy'], effect: 'Muscle-head-specific advantage for medial gastrocnemius; uncertain comparison with full ROM for lateral gastrocnemius.', certainty: 'low', trainingStatuses: ['unclear'], bodyScopes: ['muscle_specific', 'exercise_specific'], muscles: ['medial gastrocnemius', 'lateral gastrocnemius'], muscleRegions: ['study-specific ultrasound sites'], exercises: ['horizontal leg-press calf raise'], romSegments: ['full', 'lengthened_partial', 'shortened_partial'], measurementMethods: ['B-mode ultrasound'], applicabilityNotes: ['Direct evidence is limited to young women and one calf-raise setup.', 'The medial and lateral heads had different comparison results.'], limitations: ['One short study, one exercise and population; muscle thickness does not establish whole-muscle volume.'], evidence: { supports: ['RW-ROM-KASSIANO-CALF-2023'], contextualizes: ['RW-ROM-KASSIANO-2023', 'RW-ROM-WOLF-LONGITUDINAL-2025'] }, searchCutoff: '2026-08-06' }),
  claim({ id: 'ECV-ROM-ARMS-LENGTHENED-v1', claimId: 'EC-ROM-ARMS-LENGTHENED', questionId: 'EQ-HYP-006', statement: 'In resistance-trained adults, eight weeks of lengthened-partial and full-ROM training produced broadly similar hypertrophy at measured elbow-flexor and elbow-extensor sites; a trivial-to-small distal elbow-flexor difference in one small study does not establish whole-muscle superiority.', outcomes: ['hypertrophy'], effect: 'Broadly similar regional hypertrophy, with a small study-specific distal elbow-flexor signal.', certainty: 'low', trainingStatuses: ['trained'], bodyScopes: ['muscle_specific', 'exercise_specific'], muscles: ['elbow flexors', 'elbow extensors', 'biceps brachii', 'brachialis', 'triceps brachii'], muscleRegions: ['45% and 55% of humeral length', '50% and 70% of acromion-to-cubital-fossa distance'], exercises: ['preacher curl', 'supinating curl', 'overhead triceps extension', 'lat pulldown', 'bench press', 'dumbbell row'], romSegments: ['full', 'lengthened_partial'], measurementMethods: ['B-mode ultrasound'], applicabilityNotes: ['Regional ultrasound findings should not be described as whole-arm or whole-muscle superiority.', 'Both direct studies lasted eight weeks.'], limitations: ['Small and short studies; exercise packages and measurement sites differ.'], evidence: { supports: ['RW-ROM-WOLF-UPPER-2025', 'RW-ROM-HAVERS-BICEPS-2025'], contextualizes: ['RW-ROM-GSCHNEIDNER-2025', 'RW-ROM-REGIONAL-META-2025'] }, searchCutoff: '2026-08-06' }),
  claim({ id: 'ECV-ROM-QUAD-LENGTHENED-v1', claimId: 'EC-ROM-QUAD-LENGTHENED', questionId: 'EQ-HYP-006', statement: 'In one eight-week knee-extension trial, lengthened-partial and full ROM produced similar vastus lateralis muscle-thickness growth at all measured sites, while each outperformed shortened-partial ROM at selected sites.', outcomes: ['hypertrophy'], effect: 'Similar lengthened-partial versus full-ROM hypertrophy; site-specific advantage over shortened partial ROM.', certainty: 'low', trainingStatuses: ['unclear'], bodyScopes: ['muscle_specific', 'exercise_specific'], muscles: ['vastus lateralis'], muscleRegions: ['25%, 50% and 75% of femur length'], exercises: ['knee extension'], romSegments: ['full', 'lengthened_partial', 'shortened_partial'], measurementMethods: ['B-mode ultrasound'], applicabilityNotes: ['This claim is specific to vastus lateralis and knee extension.', 'Different loads were used for lengthened partial and full ROM.'], limitations: ['One short trial; loading differed by condition and the evidence is abstract-only.'], evidence: { supports: ['RW-ROM-MCMAHON-2026'], contextualizes: ['RW-ROM-VAROVIC-2025', 'RW-ROM-REGIONAL-META-2025'] }, searchCutoff: '2026-08-06' }),
  claim({ id: 'ECV-ORDER-STRENGTH-PRIORITY-v1', claimId: 'EC-ORDER-STRENGTH-PRIORITY', questionId: 'EQ-PRG-002', statement: 'Placing a priority exercise earlier in a session tends to favor strength gain in that exercise.', outcomes: ['exercise_specific_strength'], effect: 'Earlier placement favors exercise-specific strength.', certainty: 'moderate', bodyScopes: ['exercise_specific'], evidence: { supports: ['RW-ORDER-NUNES-2021'] } }),
  claim({ id: 'ECV-ORDER-HYPERTROPHY-v1', claimId: 'EC-ORDER-HYPERTROPHY', questionId: 'EQ-PRG-002', statement: 'No clear hypertrophy advantage has been shown for multi-joint-first versus single-joint-first ordering.', outcomes: ['hypertrophy'], effect: 'No clear difference detected.', certainty: 'low', evidence: { supports: ['RW-ORDER-NUNES-2021'] } }),
  claim({ id: 'ECV-PERIODIZATION-OUTCOMES-v1', claimId: 'EC-PERIODIZATION-OUTCOMES', questionId: 'EQ-PRG-003', statement: 'Volume-equated periodization may modestly improve 1RM strength, especially in trained lifters, without a clear hypertrophy advantage.', outcomes: ['maximal_strength', 'hypertrophy'], effect: 'Small strength advantage; no clear hypertrophy advantage.', certainty: 'moderate', trainingStatuses: ['trained', 'mixed'], evidence: { supports: ['RW-PERIOD-MOESGAARD-2022'], contextualizes: ['RW-ACSM-2026'] } }),
  claim({ id: 'ECV-DELOAD-PLANNED-v1', claimId: 'EC-DELOAD-PLANNED', questionId: 'EQ-PRG-003', statement: 'Evidence is insufficient to consider fixed-schedule deloads necessary or superior for everyone.', outcomes: ['maximal_strength', 'hypertrophy', 'fatigue'], effect: 'Insufficient evidence for a universal planned-deload rule.', certainty: 'very_low', evidence: { contextualizes: ['RW-DELOAD-COLEMAN-2024', 'RW-DELOAD-PANCAR-2026'] } }),
  claim({ id: 'ECV-CONCURRENT-STRENGTH-HYP-v1', claimId: 'EC-CONCURRENT-STRENGTH-HYP', questionId: 'EQ-CON-001', statement: 'Concurrent aerobic and resistance training does not show meaningful average impairment of hypertrophy or maximal strength in healthy adults.', outcomes: ['hypertrophy', 'maximal_strength'], effect: 'No meaningful average impairment detected.', certainty: 'moderate', evidence: { supports: ['RW-CON-SCHUMANN-2022', 'RW-CON-HELD-2026'] } }),
  claim({ id: 'ECV-CONCURRENT-POWER-SCHEDULE-v1', claimId: 'EC-CONCURRENT-POWER-SCHEDULE', questionId: 'EQ-CON-001', statement: 'Explosive-strength adaptations may be attenuated when endurance and resistance work occur in the same session; separation by several hours may reduce the risk.', outcomes: ['power'], effect: 'Possible attenuation, especially in the same session.', certainty: 'low', evidence: { supports: ['RW-CON-SCHUMANN-2022'], contextualizes: ['RW-CON-HELD-2026'] } }),
]

const recommendations = [
  recommendation({ id: 'ER-WEEKLY-VOLUME-HYP-DEFAULT-v1', claimVersionId: 'ECV-WEEKLY-VOLUME-HYP-v1', guidance: 'Use weekly volume as an adjustable dose rather than a mandatory universal number.', heuristic: 'Start conservatively and increase only when execution, recovery and adherence remain good.', forbidden: 'A fixed set count is optimal or mandatory for everyone.' }),
  recommendation({ id: 'ER-RIR-HYP-DEFAULT-v1', claimVersionId: 'ECV-RIR-HYP-v1', guidance: 'Most working sets can stop close to failure without reaching exact failure.', heuristic: 'Use a broad 1–3 RIR default and teach calibration without false precision.', forbidden: 'Every set must reach failure or a sharp RIR threshold is proven.' }),
  recommendation({ id: 'ER-LOAD-GOAL-DEFAULT-v1', claimVersionId: 'ECV-LOAD-GOAL-v1', guidance: 'Choose load ranges by outcome and exercise constraints.', heuristic: 'Use moderate repetitions for convenience; include heavier practice for maximal-strength goals.', forbidden: 'Only 8–12 repetitions build muscle.' }),
  recommendation({ id: 'ER-FREQUENCY-HYP-DEFAULT-v1', claimVersionId: 'ECV-FREQUENCY-HYP-v1', guidance: 'Use frequency primarily to distribute weekly volume and preserve session quality.', heuristic: 'Choose the lowest schedule complexity that supports quality and adherence.', forbidden: 'Every muscle must be trained a fixed number of times per week.' }),
  recommendation({ id: 'ER-REST-DEFAULT-v1', claimVersionId: 'ECV-REST-HYP-v1', guidance: 'Rest long enough to preserve safe technique and intended set quality.', heuristic: 'Start around 2–3 minutes for compound and 1–2 minutes for isolation work, then adjust.', forbidden: 'A single rest duration is biologically optimal for everyone.' }),
  recommendation({ id: 'ER-PROGRESSION-DOUBLE-v1', claimVersionId: 'ECV-PROGRESSION-METHOD-v1', supportingClaimVersionIds: ['ECV-PROGRESSION-ALGORITHM-v1'], guidance: 'Progress can come from repetitions or load.', heuristic: 'Use double progression as a transparent default; change sets separately.', forbidden: 'Double progression is proven optimal.' }),
  recommendation({ id: 'ER-ROM-COMFORTABLE-FULL-v1', claimVersionId: 'ECV-ROM-FULL-DEFAULT-v1', supportingClaimVersionIds: ['ECV-ROM-LENGTHENED-PARTIAL-v1', 'ECV-ROM-CALF-LENGTHENED-v1', 'ECV-ROM-ARMS-LENGTHENED-v1', 'ECV-ROM-QUAD-LENGTHENED-v1'], guidance: 'Use controlled full ROM as the general default.', heuristic: 'Offer lengthened partials only as a muscle- and exercise-specific option supported by a narrow claim.', forbidden: 'Deeper ROM is always better, lengthened partials are universally superior, or pain should be pushed through.' }),
  recommendation({ id: 'ER-ORDER-PRIORITY-FIRST-v1', claimVersionId: 'ECV-ORDER-STRENGTH-PRIORITY-v1', supportingClaimVersionIds: ['ECV-ORDER-HYPERTROPHY-v1'], guidance: 'Place the highest-priority exercise earlier.', heuristic: 'Resolve equal priorities with safety, equipment and preference constraints.', forbidden: 'Compound exercises must always come first.' }),
  recommendation({ id: 'ER-PERIODIZATION-DELOAD-v1', claimVersionId: 'ECV-PERIODIZATION-OUTCOMES-v1', supportingClaimVersionIds: ['ECV-DELOAD-PLANNED-v1'], guidance: 'Use simple variation for strength goals without claiming a hypertrophy advantage.', heuristic: 'Trigger deload decisions from persistent user signals rather than a mandatory calendar.', forbidden: 'Everyone needs a deload every fixed number of weeks.' }),
  recommendation({ id: 'ER-CONCURRENT-SCHEDULE-v1', claimVersionId: 'ECV-CONCURRENT-STRENGTH-HYP-v1', supportingClaimVersionIds: ['ECV-CONCURRENT-POWER-SCHEDULE-v1'], guidance: 'Do not remove cardio by default from strength or hypertrophy plans.', heuristic: 'When power is the priority, lift first and separate demanding sessions by hours or days.', forbidden: 'Cardio always kills gains or three hours guarantees no interference.' }),
]

const testGroup = (prefix, claimId, prompts) => prompts.map(([suffix, prompt, answerability]) => ({
  id: `AIT-${prefix}-${suffix}`,
  question: prompt,
  expectedAnswerability: answerability,
  requiredClaims: answerability === 'supported' ? [claimId] : [],
  mustInclude: ['Evidence limits and the relevant outcome.'],
  mustNotInclude: ['A guaranteed individual result or invented exact threshold.'],
}))

const aiTests = [
  ...testGroup('VOL', 'ECV-WEEKLY-VOLUME-HYP-v1', [['01', 'How many weekly chest sets?', 'supported'], ['02', 'Are 20 sets mandatory?', 'supported'], ['03', 'Should a returning novice start with 20 sets?', 'supported'], ['04', 'Should I change eight sets if I progress?', 'supported'], ['05', 'Does a press count fully for chest and triceps?', 'uncertain'], ['06', 'What exact growth percentage will 12 sets cause?', 'uncertain'], ['07', 'Thirty sets and falling performance: what now?', 'supported'], ['08', 'Acute shoulder pain: prescribe chest volume.', 'out_of_scope']]),
  ...testGroup('RIR', 'ECV-RIR-HYP-v1', [['01', 'Every set to failure?', 'supported'], ['02', 'Is two RIR useless?', 'supported'], ['03', 'Is five RIR ideal for hypertrophy?', 'supported'], ['04', 'A novice cannot estimate RIR.', 'supported'], ['05', 'Can leg extensions reach failure?', 'supported'], ['06', 'Is zero RIR exactly 7% better?', 'uncertain'], ['07', 'Technique fails before target RIR.', 'supported'], ['08', 'Which RIR treats knee pain?', 'out_of_scope']]),
  ...testGroup('LOAD', 'ECV-LOAD-GOAL-v1', [['01', 'Are 15 reps outside hypertrophy?', 'supported'], ['02', 'Can only high reps maximize 1RM?', 'supported'], ['03', 'Can lighter loads build muscle?', 'supported'], ['04', 'Are five and 30 reps always equal?', 'supported'], ['05', 'What is the exact lower %1RM threshold?', 'uncertain'], ['06', 'A light set ends far from failure.', 'supported'], ['07', 'Heavy pressing causes elbow pain.', 'out_of_scope'], ['08', 'Must a novice test 1RM?', 'supported']]),
  ...testGroup('FREQ', 'ECV-FREQUENCY-HYP-v1', [['01', 'Are legs once weekly useless?', 'supported'], ['02', 'Is three times always better than two?', 'supported'], ['03', 'Twelve sets in one session lose quality.', 'supported'], ['04', 'I can only train on weekends.', 'supported'], ['05', 'Bench once weekly for a strength goal.', 'supported'], ['06', 'Do muscles recover in exactly 48 hours?', 'uncertain'], ['07', 'High soreness between sessions.', 'supported'], ['08', 'Prescribe around disease-related fatigue.', 'out_of_scope']]),
  ...testGroup('REST', 'ECV-REST-HYP-v1', [['01', 'Rest 60 or 180 seconds for hypertrophy?', 'supported'], ['02', 'The squat timer ended but I am not ready.', 'supported'], ['03', 'Ninety seconds works for isolation sets.', 'supported'], ['04', 'Does long rest kill intensity?', 'supported'], ['05', 'Are 90 seconds proven optimal?', 'supported'], ['06', 'Exact rest for maximal strength?', 'uncertain'], ['07', 'Can circuits trade performance for time?', 'supported'], ['08', 'I feel dizzy between sets.', 'out_of_scope']]),
  ...testGroup('PRG', 'ECV-PROGRESSION-METHOD-v1', [['01', 'Must progression only increase weight?', 'supported'], ['02', 'Prove the exact best progression algorithm.', 'uncertain']]),
  ...testGroup('ROM', 'ECV-ROM-FULL-DEFAULT-v1', [['01', 'Is half ROM always worse?', 'supported'], ['02', 'Should I push deeper through squat pain?', 'out_of_scope']]),
  ...testGroup('ROMCALF', 'ECV-ROM-CALF-LENGTHENED-v1', [['01', 'Are bottom-half calf raises better than full reps for both gastrocnemius heads?', 'supported'], ['02', 'Do calf-raise results prove lengthened partials are best for every muscle?', 'supported']]),
  ...testGroup('ROMARMS', 'ECV-ROM-ARMS-LENGTHENED-v1', [['01', 'Should I replace all full-ROM curls with lengthened partials?', 'supported'], ['02', 'Did the whole biceps grow more or only one measured region?', 'supported']]),
  ...testGroup('ROMQUAD', 'ECV-ROM-QUAD-LENGTHENED-v1', [['01', 'Are lengthened partial knee extensions better than full ROM for vastus lateralis?', 'supported'], ['02', 'Can this knee-extension result be applied to squats?', 'uncertain']]),
  ...testGroup('ORDER', 'ECV-ORDER-STRENGTH-PRIORITY-v1', [['01', 'Where should bench go for a bench 1RM goal?', 'supported'], ['02', 'Will isolation first ruin hypertrophy?', 'supported']]),
  ...testGroup('PER', 'ECV-PERIODIZATION-OUTCOMES-v1', [['01', 'Is periodization mandatory for hypertrophy?', 'supported']]),
  ...testGroup('DELOAD', 'ECV-DELOAD-PLANNED-v1', [['01', 'Must every fourth week be a deload?', 'uncertain']]),
  ...testGroup('CON', 'ECV-CONCURRENT-STRENGTH-HYP-v1', [['01', 'Will cardio eat my muscle?', 'supported'], ['02', 'Hard intervals and legs in one power session?', 'supported']]),
]

const blog = (id, primaryQuestionId, workingTitle, primaryClaimVersions) => ({
  id,
  primaryQuestionId,
  workingTitle,
  searchIntent: workingTitle.toLowerCase(),
  reader: 'Healthy adult planning gym training.',
  primaryClaimVersions,
  sections: [{ heading: 'Short answer', purpose: 'Answer the query and state evidence limits.' }],
  originalValue: ['Separate research findings from the AI Trainer product heuristic.'],
  mandatoryLimitations: ['Population, outcome, certainty and unknowns.'],
  cta: 'Use AI Trainer to adapt the general principle to training constraints.',
  reviewerRequired: true,
})

const blogOutlines = [
  blog('BO-WEEKLY-VOLUME', 'EQ-HYP-001', 'How many weekly sets build muscle?', ['ECV-WEEKLY-VOLUME-HYP-v1']),
  blog('BO-RIR-FAILURE', 'EQ-HYP-002', 'Do you need to train to failure?', ['ECV-RIR-HYP-v1']),
  blog('BO-LOAD-REPS', 'EQ-HYP-003', 'How many repetitions build muscle?', ['ECV-LOAD-GOAL-v1']),
  blog('BO-ROM', 'EQ-HYP-006', 'Full or partial range of motion?', ['ECV-ROM-FULL-DEFAULT-v1', 'ECV-ROM-LENGTHENED-PARTIAL-v1', 'ECV-ROM-CALF-LENGTHENED-v1', 'ECV-ROM-ARMS-LENGTHENED-v1', 'ECV-ROM-QUAD-LENGTHENED-v1']),
  blog('BO-DELOAD', 'EQ-PRG-003', 'Do you need a deload week?', ['ECV-PERIODIZATION-OUTCOMES-v1', 'ECV-DELOAD-PLANNED-v1']),
  blog('BO-CONCURRENT', 'EQ-CON-001', 'Does cardio interfere with muscle and strength?', ['ECV-CONCURRENT-STRENGTH-HYP-v1', 'ECV-CONCURRENT-POWER-SCHEDULE-v1']),
]

export const evidencePilotFixtures = {
  version: 1,
  generatedAt: '2026-08-02T00:00:00.000Z',
  questions,
  works,
  assessments,
  claims,
  recommendations,
  aiTests,
  blogOutlines,
}
